apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: telegram-source
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: org.apache.camel.kafkaconnector.telegram.CamelTelegramSourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    topics: telegram-inbox 
    camel.source.marshal: json-jackson
    camel.source.path.type: bots
    camel.source.endpoint.authorizationToken: ${file:/opt/kafka/external-configuration/telegram-credentials/telegram-credentials.properties:token}