###########
# Kafka Streams API -> Object Detection
###########

# Topics
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: telegram-outbox
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
---

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: object-detection
  labels:
      strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  partitions: 3
---

# User
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: object-detection
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: object-detection
        operation: Read
      - resource:
          type: topic
          name: object-detection
        operation: Describe
      - resource:
          type: group
          name: object-detection
          patternType: prefix
        operation: Read
      - resource:
          type: topic
          name: telegram-outbox
        operation: Write
      - resource:
          type: topic
          name: telegram-outbox
        operation: Describe
---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: object-detection
  name: object-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
        - name: object-detection
          image: quay.io/scholzj/demo-kafka-strimzi-telegram-ml-object-detection:latest
          env:
            - name: CA_CRT
              valueFrom:
                secretKeyRef:
                  name: my-cluster-cluster-ca-cert
                  key: ca.crt
            - name: USER_CRT
              valueFrom:
                secretKeyRef:
                  name: object-detection
                  key: user.crt
            - name: USER_KEY
              valueFrom:
                secretKeyRef:
                  name: object-detection
                  key: user.key
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: APPLICATION_ID
              value: object-detection
            - name: SOURCE_TOPIC
              value: object-detection
            - name: TARGET_TOPIC
              value: telegram-outbox
            - name: LOG_LEVEL
              value: "INFO"